#! /usr/bin/env ansible-playbook
# Configure template role
# Replace 'all' with your own inventory group
---
- name: timesyncd | synchronize time
  hosts: all
  roles:
  - role: systemd-timesyncd
    tags:
    - ntp
    - time
    when: ansible_virtualization_type != 'container'
